### PR TITLE
Fix get_interfaces_ip()

### PR DESCRIPTION
**Pull request by jzohrab**
The current implementation of `get_interfaces_ip()` fails for our current setup, which returns the json shown in `test/unit/nxos/mock_data/show_ip_interface_multiple_ips.json`.  Ref issue https://github.com/napalm-automation/napalm-nxos/issues/17.

This PR builds on PR #16.  That PR has some code that I needed to ensure that the change doesn't break the existing code, and rather than artificially breaking the code up, and causing more future conflicts, I chose to build on the existing code.  The additional code in this PR is commit 0a5950d.

I will commit to updating these tests, and the tests in the other PR, when the new testing framework (also noted in PR #16) is released.  Until then, we needed to have these changes now, so I'm offering this here as a stopgap until the new framework is available.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
May I ask why didn't you open a PR **only** with the changes necessary to fix `get_interfaces_ip` (in all files, nxos.py and tests etc.) as specified in the title?
The code you proposed contains code for `get_bgp_neighbors` too. Do you need it to fix #17 by any chance?

**Comment by jzohrab** [comment]
Hey @mirceaulinic, I understand the spirit of your questions.  I have 2 reasons:
1. I needed the changes to the `FakeNXOSDevice` class to ensure that the tests worked.  I could separate it out, but that felt like make-work, and would potentially cause some conflict later.
2. I also needed to add a new class for tests, with similar notes as the `TestNXOSDriver_bgp_neighbors` tests, and the conversation recorded with me and @dbarrosop, in PR #16.  If I'd added these tests independently, it would conflict with the tests added in the other PR.  So I'm saving myself that conflict.

PR #16 works as-is, if it didn't, I'd fix it. :-)

This isn't ideal, but it felt like a a step in the right direction, even if it's imperfect.  I understand your questions, this code doesn't have to be accepted as-is, but I'm offering it anyway as this is what my team (me) has to do to make progress on our internal project, and the work here seems to make sense.

**Comment by mirceaulinic** [comment]
Many years ago git said “Let there be branches”. And here we should make use of them. #17 should be fixed and here #16 implements get_bgp_neighbors.

>  but I'm offering it anyway as this is what my team (me) has to do to make progress on our internal project, and the work here seems to make sense.

Do you agree with me that your affirmation does not make any sense? Again branches. For napalm-junos, for example, our version is more than 2000 lines long and things don’t get messed with the public repo. Can you please do the same?

You can either propose something that will fix strictly #17 and you come back later with a PR for improvements, either wait till #16 gets merged.

Please clean this up.

**Comment by jzohrab** [comment]
I understand, and I know git very well.  This way of handling things was a conscious choice on my part, so I disagree with your statement for this situation even though I support it in general for software development.

I'll close this and wait until PR #16 is merged, as that's the path of least resistance for me, and I think for the codebase too due to conflicts that will happen otherwise.  I'll leave the branch in my public repo for your review if you'd like.

**Pull request closed without merging**
