### PR TITLE
Adding get_interfaces_ip for SSH driver

### PR DESCRIPTION
**Pull request by gjim83**
Adding without any v6 test output, as local-link interfaces return `prefix_length: "N/A'` but the current model doesn't like it (only expects `int` for that key).

Added `vrf all` to commands, unless there's a good reason to only retrieve from `default`.

Kept old documents, can remove other VRF's if needed.

### CODE REVIEW

**Comment by gjim83** [comment]
Using the output currently in `show_ipv6_interface.txt` and once/if the issue with the model is fixed, the contents of `expected_result.json` would be:

```javascript
{
    "Ethernet2/3": {
        "ipv4": {
            "4.4.4.4": {
                "prefix_length": 16
            }
        },
        "ipv6": {
            "2001:db8::1": {
                "prefix_length": 10
            },
            "fe80::2ec2:60ff:fe4f:feb2": {
                "prefix_length": "N/A"
            }
        }
    },
    "Ethernet2/2": {
        "ipv4": {
            "2.2.2.2": {
                "prefix_length": 27
            },
            "3.3.3.3": {
                "prefix_length": 25
            }
        }
    },
    "Ethernet2/4": {
        "ipv6": {
            "2001:cc11:22bb:0:2ec2:60ff:fe4f:feb2": {
                "prefix_length": 64
            },
            "2001:11:2233::a1": {
                "prefix_length": 24
            },
            "fe80::2ec2:60ff:fe4f:feb2": {
                "prefix_length": "N/A"
            }
        }
    },
    "Ethernet2/1": {
        "ipv4": {
            "1.1.1.1": {
                "prefix_length": 24
            }
        }
    },
    "mgmt0": {
        "ipv4": {
            "10.0.0.71": {
                "prefix_length": 24
            }
        }
    }
}
```

**Comment by ktbyers** [comment]
@gjim83 I will try to review shortly. Thanks for your work here.

**Comment by ktbyers** [comment]
@gjim83 Right now this method only supports the 'default' VRF so I converted it back to VRF default. I also implemented the link-local to be /64 prefixes. I have a discussion open with other people on napalm on what they should be as there is some inconsistency here.

**Comment by ktbyers** [comment]
@gjim83 I am going to merge your changes in through this PR here:

https://github.com/napalm-automation/napalm-nxos/pull/123

**Pull request closed without merging**
