### PR TITLE
Handle 4 bytes ASN format

### PR DESCRIPTION
**Pull request by targuan**
<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by ktbyers** [comment]
I think we should implement this as a helper in napalm_base. I say this as other platforms will need this. 

There is a PR in napalm-ios to reimplement the get_bgp_neighbors that will also probably need this  conversion.

https://github.com/napalm-automation/napalm-ios/pull/137

**Comment by ktbyers** [comment]
@targuan Thanks for submitting this. 

I created a function in napalm-base that uses your code and makes it more reusable across the different napalm-drivers.

It is now in the released version of napalm-base. See here:

https://github.com/napalm-automation/napalm-base/pull/246/files

Can you update this to call that function?

Either that or we can close this PR and resubmit a new one.

We also need to update the requirements.txt file to use napalm-base >= 0.24.0

**Comment by targuan** [comment]
@ktbyers thanks for your feed back. I've updated this PR accordingly.

**Comment by ktbyers** [comment]
@targuan This looks fine...

do you know why we aren't parsing uptime on NX-OS. I see that we have is_up set to True, but uptime set at -1 (i.e. no value)?

**Comment by targuan** [comment]
Not sure why some values are hardcoded, maybe it's related to the cryptic format returned by the equipement for some field.
I'm actually planning to propose a more complete getter for the bgp neighbors, base on another command, as the current one doesn't return all the address families I need.

**Comment by ktbyers** [comment]
Okay, let me merge this (as those other issues are independent of this).

**Pull request merged**
