### PR TITLE
Traceroute: add vrf arg

### PR DESCRIPTION
**Pull request by mirceaulinic**
Solves #70

<!-- Make sure you have read http://napalm.readthedocs.io/en/latest/contributing/index.html --!>

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Weird error, that I'm not seeing in my env: https://travis-ci.org/napalm-automation/napalm-nxos/jobs/199103340

**Comment by dbarrosop** [comment]
Yeah, I have started to see that one as well. Fixing it is as simple from changing:

```
try:
    bla
except:
    ble
```

to:

```
try:
    bla
except Exception:
    ble
```

**Comment by mirceaulinic** [comment]
I have suspected that as well, but I didn't see that chunk of config catching the generic exception. I will double check.

**Comment by dbarrosop** [comment]
Here: https://github.com/napalm-automation/napalm-nxos/blob/8b4fe0e23da9053c1e5c414f2575c13d1501d5ed/napalm_nxos/nxos.py#L306

**Comment by mirceaulinic** [comment]
Thanks @dbarrosop

**Pull request merged**
